// Generated by CoffeeScript 1.4.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.NAN.maximumNumber = 100000000;

  NAN.NumberSet = (function() {

    function NumberSet() {
      this.numbers = [];
      this.description = "Interesting Number";
    }

    NumberSet.prototype.analyze = function(n) {
      n = parseInt(n);
      if (__indexOf.call(this.numbers, n) >= 0) {
        return {
          score: Math.max(1, n) / Math.max(1, this.numbers.indexOf(n)),
          description: this.description
        };
      }
      return {
        score: 0,
        description: null
      };
    };

    return NumberSet;

  })();

  NAN.PrimeNumberSet = (function(_super) {

    __extends(PrimeNumberSet, _super);

    PrimeNumberSet.prototype.isPrime = function(n) {
      var a;
      n = parseInt(n);
      if (n === 2) {
        return true;
      }
      if (n < 2) {
        return false;
      }
      a = 2;
      while (a * a <= n) {
        if (n % a === 0) {
          return false;
        }
        a += 1;
      }
      return true;
    };

    function PrimeNumberSet() {
      var i, _i, _ref;
      PrimeNumberSet.__super__.constructor.call(this);
      this.description = "Prime Number";
      for (i = _i = 0, _ref = NAN.maximumNumber / 1000; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (this.isPrime(i)) {
          this.numbers.push(i);
        }
      }
    }

    PrimeNumberSet.prototype.analyze = function(n) {
      var result;
      result = PrimeNumberSet.__super__.analyze.call(this, n);
      result.score *= 3;
      return result;
    };

    return PrimeNumberSet;

  })(NAN.NumberSet);

  NAN.PowerOf2NumberSet = (function(_super) {

    __extends(PowerOf2NumberSet, _super);

    function PowerOf2NumberSet() {
      var a;
      PowerOf2NumberSet.__super__.constructor.call(this);
      this.description = "Power Of 2";
      a = 1;
      while (a < NAN.maximumNumber) {
        this.numbers.push(a);
        a *= 2;
      }
    }

    return PowerOf2NumberSet;

  })(NAN.NumberSet);

  NAN.SquareNumberSet = (function(_super) {

    __extends(SquareNumberSet, _super);

    function SquareNumberSet() {
      var a, _i, _ref;
      SquareNumberSet.__super__.constructor.call(this);
      this.description = "Square Number";
      for (a = _i = 0, _ref = Math.floor(Math.sqrt(NAN.maximumNumber)); 0 <= _ref ? _i < _ref : _i > _ref; a = 0 <= _ref ? ++_i : --_i) {
        this.numbers.push(a * a);
      }
    }

    return SquareNumberSet;

  })(NAN.NumberSet);

  NAN.CubicNumberSet = (function(_super) {

    __extends(CubicNumberSet, _super);

    function CubicNumberSet() {
      var a, _i, _ref;
      CubicNumberSet.__super__.constructor.call(this);
      this.description = "Cubic Number";
      for (a = _i = 0, _ref = NAN.maximumNumber; 0 <= _ref ? _i < _ref : _i > _ref; a = 0 <= _ref ? ++_i : --_i) {
        this.numbers.push(a * a * a);
        if (a * a * a >= NAN.maximumNumber) {
          break;
        }
      }
    }

    return CubicNumberSet;

  })(NAN.NumberSet);

  NAN.FactorialNumberSet = (function(_super) {

    __extends(FactorialNumberSet, _super);

    function FactorialNumberSet() {
      var a, i, _i;
      FactorialNumberSet.__super__.constructor.call(this);
      this.description = "Factorial Number";
      a = 1;
      for (i = _i = 1; _i <= 1000; i = ++_i) {
        a = a * i;
        if (a >= NAN.maximumNumber) {
          break;
        }
        this.numbers.push(a);
      }
    }

    return FactorialNumberSet;

  })(NAN.NumberSet);

  NAN.HundredNumberSet = (function(_super) {

    __extends(HundredNumberSet, _super);

    function HundredNumberSet() {
      var a, b, i, _i, _j;
      HundredNumberSet.__super__.constructor.call(this);
      this.description = "Ends in 0s";
      a = 1;
      for (i = _i = 1; _i <= 1000; i = ++_i) {
        a = a * 10;
        for (b = _j = 1; _j <= 9; b = ++_j) {
          if (a * b >= NAN.maximumNumber) {
            break;
          }
          this.numbers.push(a * b);
        }
      }
    }

    return HundredNumberSet;

  })(NAN.NumberSet);

  NAN.AutomorphicNumberNumberSet = (function(_super) {

    __extends(AutomorphicNumberNumberSet, _super);

    function AutomorphicNumberNumberSet() {
      AutomorphicNumberNumberSet.__super__.constructor.call(this);
      this.description = "Automorphic Number";
      /*
      		a = 0
      		b = 1
      		for i in [1..1000]
      			c = a + b
      			a = b
      			b = c
      			break if a >= NAN.maximumNumber 
      			@numbers.push(a)
      */

    }

    return AutomorphicNumberNumberSet;

  })(NAN.NumberSet);

  NAN.FibonacciNumberSet = (function(_super) {

    __extends(FibonacciNumberSet, _super);

    function FibonacciNumberSet() {
      var a, b, c, i, _i;
      FibonacciNumberSet.__super__.constructor.call(this);
      this.description = "Fibonacci Number";
      a = 0;
      b = 1;
      for (i = _i = 1; _i <= 1000; i = ++_i) {
        c = a + b;
        a = b;
        b = c;
        if (a >= NAN.maximumNumber) {
          break;
        }
        this.numbers.push(a);
      }
    }

    return FibonacciNumberSet;

  })(NAN.NumberSet);

  NAN.PalindromicNumberSet = (function(_super) {

    __extends(PalindromicNumberSet, _super);

    function PalindromicNumberSet() {
      this.description = "Palindromic Number";
    }

    PalindromicNumberSet.prototype.analyze = function(n) {
      if (n.split("").reverse().join("") === n) {
        return {
          score: n.length,
          description: this.description
        };
      }
      return null;
    };

    return PalindromicNumberSet;

  })(NAN.NumberSet);

  NAN.Analyzer = (function() {

    function Analyzer() {
      var key;
      this.numberSets = [];
      for (key in NAN) {
        if (key.toString().indexOf("NumberSet") > 0) {
          this.numberSets.push(new NAN[key.toString()]);
        }
      }
    }

    Analyzer.prototype.analyze = function(n) {
      var descriptions, numberSet, propertiesCount, result, score, _i, _len, _ref;
      score = 0;
      descriptions = [];
      propertiesCount = 0;
      _ref = this.numberSets;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        numberSet = _ref[_i];
        result = numberSet.analyze(n);
        if (result === null) {
          continue;
        }
        score += result.score;
        propertiesCount += 1;
        descriptions.push(result.description);
      }
      return {
        score: Math.floor(score * propertiesCount),
        descriptions: descriptions
      };
    };

    return Analyzer;

  })();

}).call(this);
