// Generated by CoffeeScript 1.4.0
(function() {

  NAN.Score = (function() {

    function Score() {
      this.value = 0;
      this.displayedValue = 0;
      this.position = {
        x: 20,
        y: $("#container").width() / 2
      };
    }

    Score.prototype.addValue = function(points) {
      return this.value += points;
    };

    Score.prototype.update = function() {
      var delta;
      delta = (this.value - this.displayedValue) * 0.1;
      this.displayedValue += delta;
      return $("#score").html("" + (Math.floor(this.displayedValue + 0.3)));
    };

    return Score;

  })();

  NAN.NumberShow = (function() {

    function NumberShow(data) {
      this.time = 0;
      this.finished = false;
      this.getElement().show();
      this.getElement().animate({
        opacity: "0.95"
      }, 400);
      this.getElementNumber().html(data.n);
      this.getElementScore().html(data.score.toString() + " points");
      if (data.descriptions === null || data.descriptions === "") {
        data.descriptions = "Not Interesting";
      }
      this.getElementDescriptions().html(data.descriptions);
    }

    NumberShow.prototype.getElement = function() {
      return $("#number-show");
    };

    NumberShow.prototype.getElementNumber = function() {
      return $("#number-show-number");
    };

    NumberShow.prototype.getElementScore = function() {
      return $("#number-show-score");
    };

    NumberShow.prototype.getElementDescriptions = function() {
      return $("#number-show-descriptions");
    };

    NumberShow.prototype.update = function() {
      var _this = this;
      this.time += 1;
      if (this.time > 50) {
        this.getElement().animate({
          opacity: "0.0"
        }, 400);
        setTimeout(function() {
          return _this.getElement().hide(200);
        }, 400);
        return this.finished = true;
      }
    };

    return NumberShow;

  })();

}).call(this);
